name: feature_structure_generator
description: A Dart tool to generate feature structure for Flutter projects.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.8.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  lints: ^3.0.0
  json_serializable: ^6.7.1
  test: ^1.24.0
